Add Crazy Eights Game Logic Documentation
michaelkamerath/SharedServer pull request #12
Opened 2016-10-20 17:18 UTC by Shemarama

Add Crazy Eights Game Logic Documentation

2016-10-22 00:40 UTC, michaelkamerath commented
Please add your section to the SDD.tex, other than that. It looks good

2016-10-22 00:40 UTC, mikamerath approved these changes

2016-10-22 00:41 UTC, mikamerath requested changes
Please change the SDD.tex to add your Crazy Eights Documentation

2016-10-24 04:45 UTC, mikamerath approved these changes

2016-10-24 07:00 UTC, C-Merrill approved these changes

2016-10-24 07:00 UTC, merged