Initial Commit Player API Code
michaelkamerath/SharedServer pull request #13
Opened 2016-10-21 05:13 UTC by katiesweet

This commit adds the basic structure and classes for the Player API. This code is not tested yet. Ligia and I will work on adding more documentation and testing/providing unit tests for this code shortly. I am skipping the testing for this commit so that I can get this code available for other groups to reference sooner. Also, I am skipping the code review since we all looked at it yesterday and agreed upon it.

2016-10-21 21:25 UTC, michaelkamerath commented
Can you clang format this? Other than that, everything looks good

2016-10-21 22:15 UTC, mikamerath commented on PlayerAPI/Card.cpp
> +    int value;
unsigned int would be slightly more accurate

2016-10-21 22:18 UTC, mikamerath commented on PlayerAPI/Card.cpp
> +enum Suit { HEARTS, SPADES, CLUBS, DIAMONDS, UNDEFINED };
The comment has JOKER as being the last suit, this has UNDEFINED as the last suit

2016-10-21 22:31 UTC, michaelkamerath commented on PlayerAPI/Card.cpp
> +    bool operator<(Card const & b) const {
(Optional) This overload can be changed to something like
if (suit == b.getsuit())
{
  return value < b.getValue();
}
else
{
  return suit < b.getSuit();
}

2016-10-21 22:33 UTC, michaelkamerath commented on PlayerAPI/Card.cpp
> +        }
This overload also doesn't make sense for a game like hearts where there is no trump suit. This would mean that SPADES is always > HEARTS which is wrong for hearts

2016-10-21 22:36 UTC, michaelkamerath commented on PlayerAPI/Game.h
> + /*
Please change file name from Game.h to Game.hpp. h is reserved for c code, hpp is for c++ code.

2016-10-21 22:36 UTC, michaelkamerath commented on PlayerAPI/Player.h
> +/*
Please change to hpp

2016-10-21 22:41 UTC, katiesweet commented on PlayerAPI/Card.cpp
> +enum Suit { HEARTS, SPADES, CLUBS, DIAMONDS, UNDEFINED };
On Friday, we decided to not include a Joker in our deck (it can or cannot be used in Crazy Eights). The reason for the UNDEFINED suit type is that in the Player Class, there is a function called requestMove() that returns a vector of Cards. In the game Crazy Eight's, a move can consist of drawing a card from the deck. We need an UNDEFINED type to alert the Crazy Eight's game logic that they chose the draw pile instead of playing a card.

2016-10-21 22:50 UTC, katiesweet commented
Michael, thanks for reviewing this. I'm working on making some of the changes you mentioned, and will have those changes up shortly. Like it is said in the commit message, I am well aware that this code is not up to standard. We made a lot of these changes quickly in our meeting, and the reason I made a premature pull request is so that other groups would be able to reference it to start working.

2016-10-21 22:51 UTC, katiesweet commented on PlayerAPI/Card.cpp
> +        }
The only reason we put in a < operator is because I was informed that a < operator was needed in order for std::shuffle to understand what to do. It has no real meaning, and is not meant to be used by any of the logic for determining a better move or anything like that. This code was thrown in quickly during the meeting in response to that comment. I agree that it doesn't make much sense, and I need to look into if it really is necessary for the shuffle.

2016-10-21 22:52 UTC, katiesweet commented on PlayerAPI/Card.cpp
> +enum Suit { HEARTS, SPADES, CLUBS, DIAMONDS, UNDEFINED };
I meant to say, on Wednesday (not Friday), sorry!

2016-10-21 23:19 UTC, katiesweet commented
I have made the changes you've suggested, run clang format, and removed the < operator overload entirely. After testing the shuffle, I don't see why it is necessary.

2016-10-22 00:33 UTC, michaelkamerath commented
Thanks for doing all of that!

2016-10-22 00:45 UTC, mikamerath approved these changes

2016-10-24 07:08 UTC, C-Merrill requested changes
This is slightly picky, but I think you should set card values to be between 2 and 14 with 14 as Ace since all the games we are playing use Ace as the high card. It will make sorting and game logic easier.

2016-10-24 19:30 UTC, katiesweet commented
I agree that it makes sense to have Ace as high. I know that the Card class has been seen by all of the logic groups though, so I'd like to alert them of the change because it can affect the code they are working on. Do we have the list of GitHub account names for the team leaders of the logic teams yet to tag them @michaelkamerath? If not, I can pose the question on Slack.

2016-10-24 20:34 UTC, michaelkamerath commented
@katiesweet I'll be getting the list up and running tonight around 6:30

2016-10-25 05:57 UTC, katiesweet commented
To @trevorjewkes @Shemarama @adamtew @michaelkamerath :
@C-Merrill suggested that the Card class have values from 2-14 to make Ace high (see conversation above). Since you four are the team leaders of the teams directly interacting with the Player API, and may have written code with the 1-13 declaration already, I wanted your opinions/to let you know of the change before making it. Thoughts?

Also, @Frangello and I have made quite a few changes/additions to the PlayerAPI. I will be submitting an actual code review for those changes in the next day or two, so I'll be looking forward to your thoughts and opinions then. Just so you can be thinking about/implementing them before I get to the code review, a few additions are:
player.initializeHand(deck, numCardsToInitializeWith),
player.insertCardToHand(card),
player.removeCardFromHand(card) //returns false if not in hand, true if successful,
a bunch of getters/setters,
etc.

2016-10-25 19:49 UTC, michaelkamerath commented
Merging as everybody needs to access this code. A separate pull request will be needed when we update CMake lists and discuss the shared code

2016-10-25 19:49 UTC, merged