Added Hearts Logic
michaelkamerath/SharedServer pull request #23
Opened 2016-11-04 03:42 UTC by trevorjewkes

Here is the Hearts Logic. I don't have the tests yet but we will get those up ASAP. Also, I did not include a "main.cpp" file to play the Hearts Logic because it is heavily reliant on server stuff. 

@katiesweet I didn't make the changes in the Player class like we discussed at the end of class. I overheard someone talking about making other changes, so to avoid and conflicts/confusion I didn't push those changes. But after I look through it again, I will share those changes with your group.

2016-11-04 04:25 UTC, michaelkamerath commented
Please read the "creating a pull request" under documentation before creating a pull request. 
You need to clang format, alter the CMake, and be sure it actually builds

2016-11-07 19:02 UTC, trevorjewkes commented
I updated everything as you asked.

2016-11-08 01:08 UTC, michaelkamerath commented
Please use @ to invite the other logic teams and katie to the code review so we can get this reviewed before merging it

2016-11-08 05:01 UTC, katiesweet requested changes
Hi Trevor,

Thanks for submitting this code for us to look at! Look like you team has put a good amount of time into this. I have a few comments overall, as well as a few comments in line.
1. I know that the Game.hpp file might not have had everything you needed in it until this point, but Shem's team (Crazy 8's) has made some additions to it in their pull request. The game networking team is in charge of this file, so in order to get your logic to be able to communicate with the Client, I believe your Hearts Game class will need to inherit from the base Game class. Once the Crazy Eights pull request gets pulled in (it needs to be reviewed by logic and game networking first), will you please have your game inherit from this?
2. It would be really nice to have a few more comments in here to explain what is going on. After sorting through it, I think I understand what most parts of your code are doing, but having some comments would have really helped. Also, a lot of your functions are quite long. Readability would be improved a bit if these could be split up.

I'm requesting changes from this pull request solely because of the bug in line 169 of HeartsGame.cpp. The rest of the problems I've sighted are more a matter of opinion, and with only a few weeks left, I feel that if the code is correct, I think it should be committed.

2016-11-08 05:01 UTC, katiesweet commented on source/HeartsLogic/HeartsGame.cpp
> +    if ((center[i].getSuit() == lead) && (center[i].getValue() == 1))
Since we decided that Ace should be high, the card class will never return a getValue == 1. I think this should be either center[i].getValue() == 14 or center[i].getValue == ACE. Either should work.

2016-11-08 05:01 UTC, katiesweet commented on source/HeartsLogic/HeartsGame.cpp
> +{
Reading through this function, I'm just a little confused on what it is doing/ what the parameters are... Can you please explain to me what this does?

2016-11-08 05:01 UTC, katiesweet commented on source/HeartsLogic/HeartsGame.cpp
> +                           std::vector<Card>& Deck)
If you wanted to use functions built into the Player API, this function can be simplified to:

void HeartsGame::dealCards(std::vector<Player>& players, std::vector<Card>& deck)
{
    for (auto && player: players)
    {
        player.initializeHand(deck, 13);
    }
}

Also, since your vector of players is owned by the class already, you technically don't need to pass players in as a parameter.

2016-11-08 05:01 UTC, katiesweet commented on source/HeartsLogic/HeartsGame.hpp
> +{
I'm not sure why you have a class with everything in it public. If you really want to make everything in the class public, use a struct. I'd recommend, however, moving some of these functions to being private instead. Most of them should only get called by other member functions, and therefore they have no need to be public.

2016-11-08 05:01 UTC, katiesweet commented on source/HeartsLogic/HeartsGame.cpp
> +  int p) // Creats a vector of Players to play the game.
I'm a bit confused on the purpose of this function. You already have a players vector owned by the HeartsGame class that is set upon the constructor. Where would this be called?

2016-11-08 05:30 UTC, C-Merrill requested changes

2016-11-08 05:30 UTC, C-Merrill commented on source/HeartsLogic/HeartsGame.cpp
> +  if (turn > 3) turn = 0;
turn = (turn+1)%4; is cleaner

2016-11-08 05:30 UTC, C-Merrill commented on source/HeartsLogic/HeartsGame.cpp
> +  initializeDeck() // creates deck of cards taken from Card.cpp
clang does weird things with these comments in line with function signatures.  I would highly recommend placing them above the function and re-running clang format.

2016-11-08 05:30 UTC, C-Merrill commented on source/HeartsLogic/HeartsGame.hpp
> +  std::vector<Card> centerPile;
It will likely be much better to use arrays here. You know they'll always be size 4 and then you don't have to worry about which index of the vector belongs to which player. On connect the client can be told which index in the field it is and it can use that to render the field. Otherwise, we're having to keep track of turns client-side. I could be wrong, but I think arrays may be a better way to go. That said, this comment won't keep you out of a merge.

2016-11-08 05:30 UTC, C-Merrill commented on source/HeartsLogic/main.cpp
> +  std::cout << "IT BUILDS\n";
Can you work on a better test that will demonstrate to us how this class actually works?

2016-11-09 03:27 UTC, trevorjewkes commented
Updated the code as per code reviews.

2016-11-11 00:53 UTC, merged

2016-11-11 00:53 UTC, michaelkamerath commented
Merging this so we can move on. Please provide unit tests soon.