Add Crazy Eights Logic
michaelkamerath/SharedServer pull request #24
Opened 2016-11-05 20:05 UTC by Shemarama

We will have another update that features playing multiple cards at once, calculating player score at the end, and replenishing the deck.  This is still a work in progress.

@katiesweet We made some changes to Card.cpp, Card.hpp, and Game.hpp.  If you could review these changes and let us know what you think that would be great.

2016-11-06 17:51 UTC, katiesweet commented
@Shemarama, the Game file in there at the moment was the bare bones one we came up with as a group to get the Game logic going, so thanks for updating it! I agree with the extraction of initializeDeck() into Game. 

The Game class is actually owned by @droidkfx, so he should be the one confirming the changes to that class. 

Also, since these changes will affect them, I think we need approvals from @davidbrowning and @trevorjewkes as well.

2016-11-08 05:57 UTC, C-Merrill requested changes
The only change you need to make right away is with your CMakeLists. It won't even build right now the way you have it defined. My eye could be lying to me, but it looks like you need to run clang format on it as well. Overall, though, looks like excellent work.

2016-11-08 05:57 UTC, C-Merrill commented on source/CrazyEightsLogic/CMakeLists.txt
> +)
You cannot re-define the Game library here. How you define and link it depends on the intended architecture, but it cannot be called "Game" since that is defined elsewhere. It looks like you're inheriting from Game, so you would add game to the link libraries with your eights library as the target. Check that that is the proper method, because my understanding was that the logic classes were aggregates of Game, in which case the linking would be the other way.

2016-11-08 05:57 UTC, C-Merrill commented on source/CrazyEightsLogic/CrazyEightsLogic.cpp
> +    }
Why not make an undefined case, get rid of all the cases 10 and under and make a default case that converts int to string? Just a side thought

2016-11-08 05:57 UTC, C-Merrill commented on source/CrazyEightsLogic/CrazyEightsLogic.cpp
> +    turn = (turn + 1) % players.size();
I like this

2016-11-08 06:01 UTC, katiesweet approved these changes
@Shemarama this code looks like it is meant for a command line version of Crazy Eights. That is a good start, but we will need it to interface with the networking code (i.e. the code yet to be filled out in PlayerNetworking.cpp and the updateGameState message in Game) instead.

I'm approving this pull request because I think the changes to Game.cpp are good, I don't see any bugs in the code, and I clearly understood what was going on.

Even though the functions haven't been written yet, I'd suggest linking this code to the networking definitions before expanding its functionality to being able to play multiple cards. I think it is more critical.

2016-11-11 01:05 UTC, merged