Add Spades Logic
michaelkamerath/SharedServer pull request #25
Opened 2016-11-07 13:32 UTC by davidbrowning

I'm having trouble with building the project pre-changes, but I've tried to plug spades in as best I can.

2016-11-08 01:06 UTC, mikamerath commented on source/SpadesLogic/CMakeLists.txt
> +xpGetExtern(externIncs externLibs PUBLIC boost wxWidgets)
Do not add an executable for this code, it is simply a library that needs to be included into the executable.

2016-11-08 01:06 UTC, mikamerath commented on source/SpadesLogic/SpadesLogic.cpp
> +void Spades::getTrickWinner(std::vector<Card> trick, int& tw)
Please don't pass tw by reference. You could change this function to return an int, which is the position of the winner

2016-11-08 01:06 UTC, mikamerath commented on source/SpadesLogic/SpadesLogic.cpp
> +bool Spades::validMove(std::vector<Card> tr, int pl, Suit& ls, int currentTurn)
The comments right here are a little out of control, instead, try naming your variables something more comprehensive so that it is easier to read the code, rather than excessive commenting

2016-11-08 01:07 UTC, michaelkamerath commented
Please also use @ to notify Katie, the other logic group leaders, and the networking team so they can also code review this

2016-11-08 06:06 UTC, C-Merrill commented on source/SpadesLogic/CMakeLists.txt
> +demo
Please call your demo something else. It cannot be named the same as an executable that already exists (in PlayerAPI).

2016-11-08 06:30 UTC, katiesweet requested changes
@davidbrowning Thanks for writing all of this. I think there is a lot of good stuff in here, and it's good to see that you are trying to move away from the command line and instead interfacing with the networking code. 

I'm requesting changes to this code because I don't think it will compile with the second definition of requestBid and requestMove. However, the rest of my comments are just opinions that I don't think should prevent this code from getting pulled in.

2016-11-08 06:30 UTC, katiesweet commented on source/PlayerAPI/Game.hpp
> +  void updateGameStateMessage()
I'm not quite sure why this is commented out twice. Will you please just delete them instead?

2016-11-08 06:30 UTC, katiesweet commented on source/PlayerAPI/Card.cpp
> +}*/ //Makes more sense to me to have this function as a member of Game.
I agree that initializeDeck() makes more sense to be in Game.hpp than in the Card file. Just FYI, Shem's team in Crazy Eight's Logic has placed this in the main Game.hpp file, so there will most likely be a conflict once on of this code is committed.

2016-11-08 06:30 UTC, katiesweet commented on source/PlayerAPI/Player.cpp
> +	std::cout << "Bid:" << std::endl;
These functions (requestBid, requestMove) also are defined in PlayerNetworking.cpp. We broke convention and had two .cpp files to define functions for the Player.hpp file. This was so we could clearly separate which functions needed the networking team's attention and which needed ours. I think there will an error compiling since these functions are defined twice.

2016-11-08 06:30 UTC, katiesweet commented on source/PlayerAPI/Player.cpp
> +
Oops. Must have missed that getter. Thanks for adding it!

2016-11-08 06:30 UTC, katiesweet commented on source/SpadesLogic/SpadesLogic.cpp
> +bool Spades::validMove(std::vector<Card> tr, int pl, Suit& ls, int currentTurn)
I agree that the variable names could potentially be a little better. I'm not exactly sure what the 'ls' name stands for. I don't mind the comments as much as Michael though. I'd prefer that to no comments at all. However, I think breaking up this functions into its two purposes-- checking the validity of the move and checking the winner of the trick -- would make the function a little more readable since it is so long.

2016-11-08 06:30 UTC, katiesweet commented on source/SpadesLogic/SpadesLogic.cpp
> +void Spades::beginRound(int starter)
This is pretty long... I'd extract some of the work in here to a few different functions if I were you. I think it would make it a bit clearer.

2016-11-08 13:19 UTC, davidbrowning commented
You guys, this feed back is AWESOME! Thanks a million for looking at it, I'll get on the changes ASAP.

2016-11-08 13:20 UTC, davidbrowning commented on source/SpadesLogic/SpadesLogic.cpp
> +bool Spades::validMove(std::vector<Card> tr, int pl, Suit& ls, int currentTurn)
Stands for LeadSuit, but you're right, there's no reason not to use 'LeadSuit'.

2016-11-08 13:22 UTC, davidbrowning commented on source/PlayerAPI/Player.cpp
> +	std::cout << "Bid:" << std::endl;
Ah! I totally missed that! Thanks for clarifying.

2016-11-09 14:01 UTC, davidbrowning commented
Now that Michael helped me out with the externPro version conflict that I had to change in the root CMakeLists.txt (And will always change back whenever I commit) I'm getting this error when trying to build the project:

`CMake Error: CMake can not determine linker language for target: NetworkInterface`

2016-11-09 17:44 UTC, michaelkamerath commented
@davidbrowning That error is known and I will be fixing it as well as other CMake errors in a pull request this evening after the meeting. If that is the only error your getting, we'll merge it tonight.

2016-11-10 14:32 UTC, davidbrowning commented
@michaelkamerath Is this okay to be merged?

2016-11-11 01:23 UTC, merged

2016-11-11 01:23 UTC, michaelkamerath commented
Please provide Unit Tests in another pull request