Possible Linux Fix
michaelkamerath/SharedServer pull request #40
Opened 2016-11-15 19:37 UTC by michaelkamerath

I've updated the CMake to only use the /EHsc flag when compiling for MSVC, I'm unsure if this is the correct solution so I would like some testing on this for Linux.

2016-11-15 19:38 UTC, michaelkamerath commented
@katiesweet, can you verify that this fix works?

2016-11-16 22:57 UTC, katiesweet commented
@michaelkamerath 
It works! However, there are other problems after this one. Go ahead and pull it in, and I will discuss the other problems with you tonight.

2016-11-16 23:14 UTC, katiesweet requested changes

2016-11-16 23:14 UTC, katiesweet commented on CMakeLists.txt
>  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc")
Just kidding, you can't have this line in here without the if statement around it for Linux.

2016-11-17 17:05 UTC, michaelkamerath commented
@katiesweet, please verify that this works correctly. @Shemarama @davidbrowning for reference, an example of how to serialize and deserialize cards can be found in the test.cpp

2016-11-17 18:09 UTC, katiesweet commented
@michaelkamerath, it works for me! Thanks for doing this fix.

2016-11-17 18:41 UTC, Frangello requested changes
@michaelkamerath On the Card.hpp file, delete `Card::` before `serialize(Archive& ar, const unsigned int version)`
It is not valid code, only Visual Studios will compile.

2016-11-17 18:59 UTC, michaelkamerath commented
@Frangello, thanks for catching that. It has been done

2016-11-17 20:33 UTC, merged