lobby integration and mock client demo
michaelkamerath/SharedServer pull request #54
Opened 2016-11-29 13:38 UTC by droidkfx

2016-11-29 19:33 UTC, C-Merrill requested changes
Fix merge conflicts and we can get this in

2016-11-29 20:42 UTC, michaelkamerath commented
@katiesweet, can you verify this builds on Linux?

2016-11-29 20:46 UTC, C-Merrill commented
@michaelkamerath are we waiting on that linux build test before we merge?

2016-11-29 20:50 UTC, michaelkamerath commented
@C-Merrill, yes, I asked @katiesweet to do this for builds so we don't have that problem again

2016-11-29 21:51 UTC, katiesweet requested changes
Will you please fix these slashed to be "/" way instead of "\" way @droidkfx? It won't build on Linux the way it is.

Also, will you please look at issue #64 ?

2016-11-29 21:51 UTC, katiesweet commented on source/Messages/LobbyGame.hpp
> +
Please fix these slashed to be "/" direction.

2016-11-29 21:51 UTC, katiesweet commented on source/main.cpp
> +#include"Lobby.hpp"
Same with these slashes

2016-11-29 21:51 UTC, katiesweet commented on source/Lobby.hpp
All these slashed need to be changed

2016-11-29 21:51 UTC, katiesweet commented on source/NetworkInterface/mockClient.cpp
> +
These as well.

2016-11-30 20:24 UTC, droidkfx commented
Everything looks ready, also fixed #64

2016-11-30 20:25 UTC, droidkfx reviewed
I think everything is ready to go. I fixed what was requested

2016-11-30 20:36 UTC, C-Merrill commented
Nothing should be linked to the Messages library, so I fixed that. It isn't complete yet, but teams should be able to take copy the entire folder into their client project to include for deserialization of lobbygame archives.

2016-11-30 20:49 UTC, C-Merrill commented
It was missing a slash in one include, but now it builds on Windows and all tests pass. @katiesweet can you verify build and tests on linux again?

2016-11-30 20:56 UTC, katiesweet commented
I get this build error...

![screen shot 2016-11-30 at 1 56 03 pm](https://cloud.githubusercontent.com/assets/16142858/20770967/cf1f7f52-b704-11e6-9929-1fe92fe9c2e4.png)

2016-11-30 21:15 UTC, C-Merrill commented
@katiesweet I did a minor fix, but it builds both ways on mine, so I have no idea if it worked? Can you try some things if it doesn't?

2016-11-30 21:22 UTC, droidkfx commented
@C-Merrill @katiesweet I also get a clean build. but it seems to be complaining about the fact that the function returns a reference.

2016-11-30 21:28 UTC, michaelkamerath commented
@droidkfx that's exactly what's happening, you can't return a reference to a temporary value

2016-11-30 21:29 UTC, droidkfx commented
@michaelkamerath Well what should we do to fix it then. It needs to return a reference so that the lobby can edit the actual game being found, this is just an edge case handler that is causing the problem.

2016-11-30 21:30 UTC, michaelkamerath commented
@droidkfx I would create a variable of GameType::UNKNOWN and pass that into the function

2016-11-30 21:32 UTC, katiesweet commented
Now it builds, runs just fine, and all the tests pass, but it still throws a warning.

![screen shot 2016-11-30 at 2 30 34 pm](https://cloud.githubusercontent.com/assets/16142858/20772153/a40eee1a-b709-11e6-949f-71b0574568bb.png)

I can look at it more if you need, but I won't be available to do so until about 4:00.

2016-11-30 21:35 UTC, droidkfx commented
@michaelkamerath I don't understand what you mean or how that would fix the problem.

2016-11-30 21:35 UTC, C-Merrill commented
It looks like the reference to a temporary object is dangerous, I guess. We could do what Michael's saying and have a lobbygame member of lobby that we can return a reference to, or we can make the function return a pointer and return a nullptr instead of an undefined game.

2016-11-30 21:36 UTC, michaelkamerath commented
@droidkfx basically what @C-Merrill is saying, he just said it much better. I would prefer the pointer route but either one is a viable option.

2016-11-30 21:39 UTC, C-Merrill commented
@katiesweet try this at least as a temporary solution. We may change to pointers, but this will work, I think

2016-11-30 21:48 UTC, michaelkamerath commented
If it works and builds on both Windows and Linux and passes the unit tests after this, we'll merge it in. Something that I'll be doing over the next few days is trying to solve the many compiler warning we receive when building.

2016-11-30 21:51 UTC, droidkfx commented
> If it works and builds on both Windows and Linux and passes the unit tests after this, we'll merge it in. 


@michaelkamerath @C-Merrill Yay, if it fits it ships!!

2016-11-30 23:26 UTC, katiesweet commented
@michaelkamerath @C-Merrill  @droidkfx We are good to go! 👍

2016-11-30 23:54 UTC, C-Merrill approved these changes

2016-11-30 23:54 UTC, merged