I'm working on making spades logic easier to deal with
michaelkamerath/SharedServer pull request #55
Opened 2016-11-29 17:21 UTC by davidbrowning

I also wrote a test for my smallest function to see if I did it right

2016-11-29 19:37 UTC, C-Merrill reviewed
I'd like to see unit tests. The code looks good otherwise, but I won't really know without unit tests

2016-11-29 19:40 UTC, C-Merrill commented on test/Test.cpp
> +	}
I think you've done this right. I'm not sure if those two things are supposed to be equal.

2016-11-29 19:54 UTC, michaelkamerath commented
Before this is merged, wait until we have the Linux fixes. Then fix the merge conflicts

2016-11-29 19:54 UTC, C-Merrill commented
You've got merge conflicts now.

2016-11-29 20:47 UTC, C-Merrill commented
Fix merge conflicts and request katie to test linux build

2016-11-29 21:31 UTC, davidbrowning commented
Fixed the merge conflict

2016-11-29 22:53 UTC, katiesweet requested changes
@davidbrowning will you please change those slashes? They need to be the other way to build on linux. Other than that, it builds just fine. However, your unit tests aren't passing...

![screen shot 2016-11-29 at 3 50 19 pm](https://cloud.githubusercontent.com/assets/16142858/20732401/c71dec76-b64b-11e6-8851-19be1fa8d773.png)

2016-11-29 22:53 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +
Will you please changes these slashes to go the other way? It doesn't build on linux as is.

2016-11-30 04:19 UTC, davidbrowning commented
Done! Sorry about that and...yeah that test was only supposed to go to 4. whoops

2016-11-30 04:27 UTC, katiesweet commented
Builds on Linux! Thanks for making those changes @davidbrowning!

2016-11-30 23:58 UTC, C-Merrill approved these changes
This builds and looks good. @michaelkamerath good to merge?

2016-12-01 00:21 UTC, C-Merrill commented
I ran clang format because it needed it and also to see what changes were actually in the pull request other than format differences.
@davidbrowning remember to run clang format in the future

2016-12-01 00:47 UTC, michaelkamerath commented
@davidbrowning Thanks for doing this, Please comment on what issues this worked with so we can keep track

2016-12-01 00:47 UTC, merged