Added unit tests and updated logic
michaelkamerath/SharedServer pull request #65
Opened 2016-11-30 00:23 UTC by Shemarama

2016-11-30 00:33 UTC, mikamerath requested changes

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +    players[turn].requestMove();  // request move function instead of stuff above
Please use .at(turn) instead of [turn], it is much safer

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +        playerCards = players[getTurn()].getHand();
Same as above

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +      if (cardIndex >= 0 && isValidCard(playerCards[cardIndex]))
Same as above

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
>                    << playerCards[cardIndex].getValue() << std::endl;
All of these, same as above

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +  Suit selection = players[turn].receivedSuit();
Same as above

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +    players[turn].requestSuit();
Same as above

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +    players[turn].requestMove();
Same as above

2016-11-30 00:33 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +  players[turn].removeCardFromHand(card);
Same as above

2016-11-30 00:33 UTC, michaelkamerath commented on test/Test.cpp
> +    BOOST_CHECK_EQUAL(players[i].getId(), crazyEights.getPlayers().at(i).getId());
Same as above

2016-11-30 00:37 UTC, trevorjewkes commented on source/GameLogic/CrazyEightsLogic.cpp
> +    players[turn].requestMove();  // request move function instead of stuff above
@michaelkamerath Could you please explain to me why it is safer. Everything that I have read says that it doesn't really make a difference. Yes there is bounds checking, but you still have to handle it or else it crashes. I may just not be understanding. Thanks.

2016-11-30 01:07 UTC, Shemarama commented
@michaelkamerath @gitCameron Okay, I made the changes

2016-11-30 04:07 UTC, katiesweet requested changes
Hi @Shemarama @gitCameron 
The player vector had to be changed from std::vector<Player> to std::vector<std::shared_ptr<Player>>. I'm afraid this is going to cause a bit of an issue trying to compile your code...

2016-11-30 04:07 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
> +      player.setValidateMove([this](Card c){isValidCard(c);});
Unfortunately, the player vector got changed to a vector of shared pointers to Players in order to interface with the networking appropriately. This will not build as is... I think that a lot of your code that uses 'player' may need to be changed to account for this. Sorry!

2016-11-30 04:07 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
> +        playerCards = players.at(getTurn()).getHand();
Here is another example. I think this needs to be players.at(getTurn())->getHand();

2016-11-30 04:07 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
Same here.
players.at(turn)->requestMove();

2016-11-30 04:07 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
>      std::cout << "Player Card " << i << ": " << rank << " of " << suit
Here too.

2016-11-30 04:07 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
> +  Suit selection = players.at(turn).receivedSuit();
I think getPlayers returns a std::vector<std::shared_pointer<Player>>... then you'd also need players.at(turn)->receivedSuit()

2016-11-30 04:22 UTC, Shemarama commented
@katiesweet @gitCameron Thanks for these reviews, I added the pointer syntax changes

2016-11-30 04:44 UTC, katiesweet requested changes
There are some more build issues here... sorry! @Shemarama @gitCameron... will you guys please try to build this on your machines?

2016-11-30 04:44 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.hpp
>    std::string convertSuitToString(Suit suit);
Here this takes in a vector of cards...

2016-11-30 04:44 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
> +      player->setValidateSuit([this](Suit s){validateSuit(s);});
Here this just takes in a single card for isValidCard, and a suit for validateSuit

2016-11-30 04:44 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
> +{
This doesn't have an argument...

2016-12-01 00:58 UTC, michaelkamerath commented
@Shemarama, don't worry about the merge conflicts in Test.cpp, I or @C-Merrill will deal with those. However, you should deal with the conflicts in Player.cpp to be sure everything is the way you want it.

2016-12-01 04:38 UTC, C-Merrill requested changes
Basically, you still have a lot of build errors to take care of. I outlined some of them, but there are lots more to fix.

2016-12-01 04:38 UTC, C-Merrill commented on test/Test.cpp
> +  Player player4(4, "144.39.162.007");
There's no constructor for ip address. @katiesweet would it be possible to make one for these unit tests so they we don't have to try to make a connection to construct players?

2016-12-01 04:38 UTC, C-Merrill commented on test/Test.cpp
> +  players.push_back(player4);
You can't push Players onto a vector of pointers to Players

2016-12-01 04:38 UTC, C-Merrill commented on test/Test.cpp
> +BOOST_CHECK_EQUAL(crazyEightsDrawCard)
Needs to be BOOST_AUTO_TEST_CASE

2016-12-01 04:38 UTC, C-Merrill commented on test/Test.cpp
> +  BOOST_CHECK_EQUAL(crazyEights.getPlayers().at(0)->isGameOver(), 1);
You're trying to call crazyeights methods from player.

2016-12-01 04:38 UTC, C-Merrill commented on test/Test.cpp
> +  BOOST_CHECK_EQUAL(crazyEights.getCardScoreValue(crad3), 10);
Typo

2016-12-01 04:38 UTC, C-Merrill commented on source/PlayerAPI/Player.cpp
> +}
Why are you duplicating these?

2016-12-01 05:10 UTC, Shemarama commented
@C-Merrill @katiesweet  still working on unit tests

2016-12-01 06:15 UTC, C-Merrill commented
I think we can accept this once unit tests build and pass

2016-12-01 19:23 UTC, C-Merrill commented
Still waiting on a successful CrazyEightsGameOver test case

2016-12-01 20:01 UTC, mikamerath requested changes

2016-12-01 20:01 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +  s = GAME_OVER;
When this function is called, calculate final scores, then send updateGameStatusMessage to all of the players

2016-12-01 20:01 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +    UpdateGameStateMessage();
These next two functions need to be deleted

2016-12-01 20:01 UTC, michaelkamerath commented on source/GameLogic/CrazyEightsLogic.cpp
> +void CrazyEightsLogic::start()
Start needs to request a move from the first player

2016-12-01 21:39 UTC, C-Merrill commented
Builds, but tests don't all pass and I'm not sure which test case it is.

2016-12-02 02:42 UTC, katiesweet requested changes
We are getting so close! I just think one more thing @gitCameron.

2016-12-02 02:42 UTC, katiesweet commented on source/GameLogic/CrazyEightsLogic.cpp
> +      deck.erase(std::remove(deck.begin(), deck.end(), card), deck.end());
I'm not sure about doing initializeDeck() here. That will repopulate it with 52 cards, including the cards that are on each players hand. It might be better to do something like...

Card top = getDiscardPile.back();
discardPile.pop_back();
deck = discardPile;
std::random_device rd;
std::mt19937 generator(rd());
std::shuffle(deck.begin(), deck.end(), generator)
discardPile.clear();
discardPile.push_back(top);

in a separate function.

2016-12-02 07:55 UTC, C-Merrill commented
@michaelkamerath, this should probably have been done elsewhere, but in looking at why tests weren't passing for this pull request, I resolved #72. Turns out, it's just that no buffer is there to write to because the connection hasn't connected to anything. I wrapped the code in write in an if statement so the exception isn't thrown.

@Shemarama, your second-to-last test still isn't passing and I'm going to let your team figure that one out. Please do it promptly. Thanks

2016-12-02 16:47 UTC, gitCameron commented
@C-Merrill Do you know the name of the test that wasn't passing for CrazyEights?

2016-12-02 18:24 UTC, C-Merrill commented
@Shemarama ValidMove doesn't pass for me

2016-12-02 18:28 UTC, C-Merrill commented
This is what the output for that test case looks like when I run test.exe.
<img width="527" alt="capture" src="https://cloud.githubusercontent.com/assets/15592298/20845461/7034333c-b882-11e6-8616-f7d9f88201c2.PNG">

2016-12-02 22:41 UTC, gitCameron commented
@C-Merrill Hey I fixed the unit test created a pull request to @Shemarama so he should be creating a pull request to fix the problem.  I had to add a setDiscardPile to Game.cpp for this to work.

2016-12-03 00:16 UTC, C-Merrill commented
This has got 51 build errors now. Maybe you resolved merge conflicts incorrectly?

2016-12-03 00:28 UTC, Shemarama commented
@C-Merrill @gitCameron 
Okay, we will look into that

2016-12-03 00:31 UTC, C-Merrill commented
@Shemarama what did you merge in commit c7bd0cb?

2016-12-03 01:09 UTC, closed without merging

2016-12-03 01:14 UTC, C-Merrill commented
@Shemarama, I think there was just a small mistake in your merge. I've fixed it.