Impliment PlayerAPI
michaelkamerath/SharedServer pull request #70
Opened 2016-12-01 02:59 UTC by davidbrowning

I think this is how the callbacks are going to work. Let me know if something needs to be changed. Still need to implement the update scoring functions.

2016-12-01 04:08 UTC, C-Merrill commented
@katiesweet can you verify the functionality here?
@davidbrowning let's get going on those unit tests

2016-12-01 04:19 UTC, katiesweet reviewed
I think the way you're doing callbacks should work... It was not quite the way I had in mind to do this, but I don't see why it wouldn't...

2016-12-01 04:19 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
>      p->setValidateBid([this](int b) { receiveBid(b); });
Not sure you need this line since you have it in the constructor...

2016-12-01 04:32 UTC, davidbrowning commented on source/GameLogic/SpadesLogic.cpp
>      p->setValidateBid([this](int b) { receiveBid(b); });
You're totally right, changing right now.

2016-12-01 22:40 UTC, davidbrowning commented
Based on what we did in class, I'm thinking this how the logic is supposed to work.

2016-12-01 22:48 UTC, katiesweet requested changes
@davidbrowning Overall, this looks a ton better! Good work! Let me know if you have questions about any of my comments. 

Two more things... 1. I'm a bit concerned about your getNextPlayer() function. It only increments plId, never sets it back to 0, so it'll call turn 0 over and over again once it hits plId = 3. 

Also, there is a lot of legacy code in here from other versions of your game. It would help readability quite a bit if it were cleaned up a little.

2016-12-01 22:48 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +      s = ROUND_OVER;
This isn't totally necessary, but it could be nice to extract this section into a roundOver() function

2016-12-01 22:48 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +      for (auto player : players)
Maybe a startNewRound() function as well... again, not necessary, but a thought. 

Also, when starting a new round, you need to call player.startNewRound() to manage the updating of players scores, reseting round score, reseting their bid, etc.

2016-12-01 22:48 UTC, katiesweet commented on source/GameLogic/SpadesLogic.hpp
> +  Card movePlaceHolder;
You might be able to get rid of these bidPlaceHolder/morePlaceHolder since we went a different route now.

2016-12-01 22:48 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +  trick.push_back(c);
You could wait to do this until after you know it is valid... Also, when are your removing this card from the players hand?

2016-12-02 15:39 UTC, davidbrowning commented on source/GameLogic/SpadesLogic.cpp
> +  trick.push_back(c);
I suppose so, but I felt it was easier to get the card to the validMove function this way and then I only have to change it when an invalid move is played (which is hopefully a pretty small number of times if we really are playing with 4 humans).

2016-12-02 15:56 UTC, davidbrowning commented
getNextPlayer() does return 0 whenever it receives 3 (or if something terrible happened something higher than 3).

2016-12-02 16:41 UTC, katiesweet requested changes
@davidbrowning This is looking good! Sorry about the getNextPlayer function. I misinterpreted what was going on. However, I still think we have an issue where we are never removing the card from the players hand after they make a move.

2016-12-02 16:41 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +  trick.push_back(c);
This line isn't necessarily the issue...
What I think is the problem is that you are adding the card to the trick, but you are never removing that card from the players hand. Down below, you are inserting it back into the hand if it's an invalid move, but it was never removed from the hand in the first place, so you'd have two of the same card in the hand...

2016-12-02 16:49 UTC, davidbrowning commented on source/GameLogic/SpadesLogic.cpp
> +  trick.push_back(c);
Ah now I see. I'll get right on it

2016-12-02 17:03 UTC, davidbrowning commented on source/GameLogic/SpadesLogic.cpp
> +  trick.push_back(c);
So it should just be that line that fixes it right?

 +  players.at(turn)->removeCardFromHand(c);

2016-12-02 18:02 UTC, katiesweet commented
Yep, I think that should do it. Thanks @davidbrowning! 

@C-Merrill and @michaelkamerath I think this one is about ready to go. Will you please look over it quickly?

2016-12-02 18:16 UTC, katiesweet requested changes
Nevermind, sorry guys, one more quick thing @davidbrowning. You aren't calling UpdateGameStateMessage() besides at roundOver/gameOver. This is the function that updates everyone's GUI's with what is going on. Therefore, after every turn is over (before requesting a move from someone else), pleas call UpdateGameStateMessage() to alert everyone of the card that has been played.

2016-12-02 18:16 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +    players.at(turn)->requestMove();
You should probably UpdateGameStateMessage() before this line or after you've determined it is a valid move. This is because once you've played a card onto the trick, everyone is going to want to update their GUI's to reflect that.

2016-12-02 18:16 UTC, katiesweet commented on source/GameLogic/SpadesLogic.cpp
> +      players.at(turn)->requestMove();
Same here. It would be nice to have an UpdateGameStateMessage() above this requestMove since you generally want to update your GUI after someone finishes their turn/you cleared the field since a trick is over.

2016-12-02 18:34 UTC, davidbrowning commented
Cool! I wasn't sure what exactly that one did so I'll put that in as soon
as I can.

On Dec 2, 2016 11:16 AM, "katiesweet" <notifications@github.com> wrote:

> *@katiesweet* requested changes on this pull request.
>
> Nevermind, sorry guys, one more quick thing @davidbrowning
> <https://github.com/davidbrowning>. You aren't calling
> UpdateGameStateMessage() besides at roundOver/gameOver. This is the
> function that updates everyone's GUI's with what is going on. Therefore,
> after every turn is over (before requesting a move from someone else),
> pleas call UpdateGameStateMessage() to alert everyone of the card that has
> been played.
> ------------------------------
>
> In source/GameLogic/SpadesLogic.cpp
> <https://github.com/michaelkamerath/SharedServer/pull/70#pullrequestreview-11211210>
> :
>
> > -  // the return card is coming here!!
> +  players.at(turn)->removeCardFromHand(c);
> +  trick.push_back(c);
> +  if (validMove())
> +  {
> +    turn = getNextPlayer(turn);
> +  }
> +  else
> +  {
> +    auto c = trick.back();
> +    players.at(turn)->insertCardToHand(c);
> +    trick.pop_back();
> +  }
> +  if (trick.size() < 4)
> +  {
> +    players.at(turn)->requestMove();
>
> You should probably UpdateGameStateMessage() before this line or after
> you've determined it is a valid move. This is because once you've played a
> card onto the trick, everyone is going to want to update their GUI's to
> reflect that.
> ------------------------------
>
> In source/GameLogic/SpadesLogic.cpp
> <https://github.com/michaelkamerath/SharedServer/pull/70#pullrequestreview-11211210>
> :
>
> > +  {
> +    players.at(turn)->requestMove();
> +  }
> +  else
> +  {
> +    trickWinner = getTrickWinner(trick, trickWinner);
> +    if (players.at(turn)->getHand().size() < 1)
> +    {
> +     roundOver();
> +     startNewRound();
> +    }
> +    else
> +    {
> +      turn = trickWinner;
> +      players.at(turn)->incrementTricksWon();
> +      players.at(turn)->requestMove();
>
> Same here. It would be nice to have an UpdateGameStateMessage() above this
> requestMove since you generally want to update your GUI after someone
> finishes their turn/you cleared the field since a trick is over.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/michaelkamerath/SharedServer/pull/70#pullrequestreview-11211210>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/APW1YhXU7aBJdXiR_t9XA1ZrXQSF1uQVks5rEGB3gaJpZM4LA81j>
> .
>

2016-12-02 18:38 UTC, C-Merrill commented
@katiesweet check linux build once that change comes in and I think we can merge this once that's verified.

2016-12-02 19:10 UTC, davidbrowning commented
I don't have the linux build working on my machine. @adamtew can you pull and build it?

2016-12-03 00:21 UTC, katiesweet commented
Builds fine for me! I think this one is ready @davidbrowning @C-Merrill @michaelkamerath !

2016-12-03 07:26 UTC, C-Merrill commented
I merged master in to make sure memory leaks while running tests were those that were already solve in Shem's merge. We're good to go.

2016-12-03 07:26 UTC, merged