Adding simple AI to Server
michaelkamerath/SharedServer pull request #71
Opened 2016-12-01 06:49 UTC by katiesweet

Here is the initial commit for the basic AI on the server. 

@michaelkamerath @C-Merrill Will you guys please do a review of this?

@droidkfx These players should now be able to be added to games if they aren't full

@gitCameron @Shemarama @davidbrowning @trevorjewkes Creating a game with all AI players might allow you to check if you are interfacing with the API correctly. 

Also, @trevorjewkes I'll add the passCards AI implementation once you push the code for the passCards functionality into Player. I would have added it now, but I figured that would cause a conflict with your pull request.

2016-12-01 16:28 UTC, mikamerath requested changes

2016-12-01 16:28 UTC, michaelkamerath commented on source/AI/AI.cpp
> +    move = hand[numCardsTriedToPlay];
Please use .at(numCardsTriedToPlay), or, an even better solution would be using a for each loop instead of a range based loop

2016-12-01 16:28 UTC, michaelkamerath commented on source/PlayerAPI/Player.hpp
> +protected:
Why did you make this protected instead of private?

2016-12-01 16:41 UTC, katiesweet commented on source/AI/AI.cpp
> +    move = hand[numCardsTriedToPlay];
I'll change it to the at, but I don't think the range based loop will work. This is because validateMove doesn't return anything. This would require a change in existing code. (We'd have to change the API and all logic teams would have to follow suit. If it's an invalid move, all logic does is requestMove again. Our API then needs to keep track of if they'd already played a card so they won't try playing it again. In Eights, they need to know if they've played all the cards so that it can request a draw.

2016-12-01 16:42 UTC, katiesweet commented on source/PlayerAPI/Player.hpp
> +protected:
I thought it would be appropriate for the AI to be able to access its hand, etc. since it inherits from Player. However, now that I'm thinking about it, the AI should be able to get that information from updateGameStatus(State?) as well. Which way do your prefer?

2016-12-01 18:34 UTC, trevorjewkes approved these changes

2016-12-01 21:27 UTC, C-Merrill approved these changes
Okay this looks really good. Thanks @katiesweet

2016-12-02 18:38 UTC, C-Merrill commented
@michaelkamerath  anything holding us back on merging this?

2016-12-02 19:34 UTC, mikamerath approved these changes

2016-12-02 19:34 UTC, michaelkamerath commented
@katiesweet @C-Merrill, everything looks good, thanks for getting this done.

2016-12-02 19:34 UTC, merged